gnu-tests: add a list of required passing gnu test

diff --git a/.github/workflows/GnuTests.yml b/.github/workflows/GnuTests.yml
--- a/.github/workflows/GnuTests.yml
+++ b/.github/workflows/GnuTests.yml
@@ -56,6 +56,20 @@ jobs:
         LOG_FILE=gnu/tests/test-suite.log
         if test -f "$LOG_FILE"
         then
+            PASSING=$(sed -n "s/^PASS: \(.\+\)/\1/p" "$LOG_FILE")
+            for LINE in $PASSING
+            do
+              if ! grep -Fxq $LINE uutils/passing-gnu-tests.txt; then
+                echo "::error ::Unexpected passing GNU test: $LINE. Please consider adding $LINE to passing-gnu-tests.txt"
+              fi
+            done
+            for LINE in $(cat uutils/passing-gnu-tests.txt)
+            do
+              if ! grep -Fxq $LINE<<<"$PASSING"
+              then
+                echo "::error ::GNU test failed: $LINE. passing-gnu-tests.txt contains $LINE, so it is expected to pass."
+              fi
+            done
             TOTAL=$(sed -n "s/.*# TOTAL: \(.*\)/\1/p"  "$LOG_FILE"|tr -d '\r'|head -n1)
             PASS=$(sed -n "s/.*# PASS: \(.*\)/\1/p" "$LOG_FILE"|tr -d '\r'|head -n1)
             SKIP=$(sed -n "s/.*# SKIP: \(.*\)/\1/p" "$LOG_FILE"|tr -d '\r'|head -n1)
